-- CUENTAS

-- SELECIONAR EL NUMERO DE CUENTA Y SALDO DE TODAS LAS CUENTAS CON SALDO MAYOR A 100 Y MENOR A 100
select *  from cuentas
where saldo > money(100) and saldo <  money(1000)

-- SLECICONAR LAS CUENTAS ENTRE EL DIA DE HOY Y HASTA HACE 1 AÑO
SELECT * FROM cuentas
WHERE fecha_creacion
BETWEEN '2023-02-16' AND '2024-02-16';



