-- VIDEOJUEGOS

select * from videojuegos

--- LISTAR LOS REGISTROS DE VIEDEOJUEGOS CON UN NOMBRE CONTENGA LA LETA C O N VOLARION DE 7
SELECT * FROM videojuegos
WHERE nombre LIKE '%C%' OR valor = 7;


-- SELECCIONAR VIEDEOJUEGOS CON UN CODIGO ENTRE 3 Y 7 O UNA VALORACION DE 7
SELECT * FROM videojuegos
WHERE codigo BETWEEN 3 AND 7 OR valor = 7;


-- SELECCIONAR VIDEOJUEGOS DE GUERRA CON UNA VALORACION MAYOR A  7 Y QUE EN SU NOMBRE ...
SELECT * FROM videojuegos
WHERE valor > 7 AND nombre LIKE '%C' OR valor > 8 AND nombre LIKE 'D%';